title: Quantitative Finance Studies
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
color_scheme: dark

url: https://asharbutt.github.io/MyWebsite

aux_links:
  Template Repository: https://github.com/asharbutt/MyWebsite

math_engine: mathjax
compress_html:
  blanklines: true
