title: Quantitative Finance Studies
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
color_scheme: dark

url: https://asharbutt.github.io/MyWebsite

aux_links:
  Template Repository: https://github.com/asharbutt/MyWebsite

<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
</script>
