title: Quantitative Finance Studies
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://asharbutt.github.io/MyWebsite

aux_links:
  Template Repository: https://github.com/asharbutt/MyWebsite
